### PR TITLE
[#96731606] added GET and POST comment methods

### PR DESCRIPTION
**Pull request by slamice**
This PR adds a GET and POST to order comments. This means customers can get and create comments on orders.

TL;DR
---------

After this is merged this needs to be updated to [pypi](https://pypi.python.org/pypi).

### CODE REVIEW

**Comment by kelvintaywl** [comment]
@slamice perhaps we can update the [Changelog file](https://github.com/gengo/gengo-python/blob/master/CHANGELOG.rst) as well for this update

**Comment by slamice** [comment]
@kelvintaywl I wish I knew about the change log back in v. 0.1.18. It's not consistent but I will mention the new endpoints in teh changelog.

**Comment by hayate** [comment]
LGTM

**Comment by kelvintaywl** [comment]
LGTM :camel:

**Pull request merged**
