### PR TITLE
[#96731606] fixed calls to customer-api instead of g

### PR DESCRIPTION
**Pull request by slamice**
This pr changes the routing to customer-api instead of G.

TL;DR
---------
- Previously routed G, now routing to customer-api. See [this pr](https://github.com/gengo/customer-api/pull/355) for more details.
- The url param style remains the same as job comments for v2 consistency

### CODE REVIEW

**Comment by kelvintaywl** [comment]
LGTM :ramen:

**Comment by hayate** [comment]
LGTM :spaghetti:

**Comment by yugui** [comment]
lgtm

**Comment by chris-erickson** [comment]
Reminder to update the [changelog](https://github.com/gengo/gengo-python/blob/master/CHANGELOG.rst) I created for you and the releases.  It helps us know what updates to be concerned with.

**Comment by hayate** [comment]
thanks @chris-erickson 
@slamice could you please update the changelog with your recent changes?

**Pull request merged**
